# -*- coding: utf-8 -*-
"""PDF_Contract_Renamer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHWHmSvBm7LNW0QFzNtNEUGiNm3HcuQY

# 📄 PDF Contract Renamer
This notebook reads PDF files, extracts the contract/agreement number from each one, and renames the files accordingly.

**`/` in contract numbers are automatically replaced with `_`**
e.g. `0004/HR-PC/IV/22` → `0004_HR-PC_IV_22.pdf`

---
### Steps:
1. Run **Cell 1** — installs required library
2. Run **Cell 2** — uploads your PDF files
3. Run **Cell 3** — preview renames (dry run, no changes yet)
4. Run **Cell 4** — rename files and download them as a ZIP
"""

# ── CELL 1: Install dependency ────────────────────────────────────────────────
!pip install pdfplumber -q
print("✅ pdfplumber installed")

# ── CELL 2: Upload your PDF files ────────────────────────────────────────────
import os
from google.colab import files

WORK_DIR = "/content/pdfs"
os.makedirs(WORK_DIR, exist_ok=True)

print("📂 Please select all your PDF files to upload...")
uploaded = files.upload()

# Move uploaded files into the work folder
for filename in uploaded:
    src = filename
    dst = os.path.join(WORK_DIR, filename)
    os.replace(src, dst)

pdf_count = len([f for f in os.listdir(WORK_DIR) if f.lower().endswith(".pdf")])
print(f"\n✅ {pdf_count} PDF file(s) ready in {WORK_DIR}")

# ── CELL 3: Preview renames (DRY RUN — nothing is changed yet) ───────────────
import re
import pdfplumber

# Pattern matches contract numbers like:
CONTRACT_PATTERN = re.compile(
    r'\b([A-Z0-9][A-Z0-9\-]{0,20}(?:/[A-Z0-9][A-Z0-9\-]{0,20}){2,})\b'
)

# These phrases appear immediately before the ORIGINAL agreement number
# in the recitals/pendahuluan section (page 2+), NOT the addendum header
RECITAL_ANCHORS = [
    "Insert_your_anchors_here"  
]

# These mark the addendum's OWN reference number in the header — skip these
HEADER_ANCHORS = [
    "Insert","your","anchor","Here"
]

def extract_contract_number(pdf_path):
    """Extract the ORIGINAL agreement number from the recitals section."""
    try:
        with pdfplumber.open(pdf_path) as pdf:
            pages_text = []
            for page in pdf.pages:
                pages_text.append(page.extract_text() or "")
    except Exception as e:
        print(f"  [ERROR] Could not read file: {e}")
        return None

    full_text = "\n".join(pages_text)
    lines = full_text.splitlines()

    # ── Strategy 1: find the number specifically near recital anchor phrases ──
    # These phrases appear right before the ORIGINAL agreement number
    for i, line in enumerate(lines):
        line_lower = line.lower()
        # Skip lines that are part of the addendum header
        if any(h in line_lower for h in HEADER_ANCHORS):
            continue
        if any(kw in line_lower for kw in RECITAL_ANCHORS):
            # Search this line and the next 2 lines for a contract number
            block = " ".join(lines[i:i+3])
            match = CONTRACT_PATTERN.search(block)
            if match:
                return match.group(1)

    # ── Strategy 2: look from page 2 onwards, skip the first page entirely ───
    # The addendum's own number is always on page 1; the original is on page 2+
    if len(pages_text) > 1:
        remaining_text = "\n".join(pages_text[1:])
        match = CONTRACT_PATTERN.search(remaining_text)
        if match:
            return match.group(1)

    # ── Strategy 3: fallback — scan whole doc (least preferred) ──────────────
    match = CONTRACT_PATTERN.search(full_text)
    return match.group(1) if match else None

def safe_filename(contract_number):
    """Replace '/' with '_' to make the contract number filesystem-safe."""
    return contract_number.replace("/", "_")


# ── Run dry-run preview ───────────────────────────────────────────────────────
pdf_files = sorted([f for f in os.listdir(WORK_DIR) if f.lower().endswith(".pdf")])

if not pdf_files:
    print("⚠️  No PDF files found. Please run Cell 2 first.")
else:
    print(f"Found {len(pdf_files)} PDF file(s)\n")
    print(f"{'ORIGINAL FILENAME':<45} {'→':^3} {'NEW FILENAME'}")
    print("─" * 90)

    preview_map = {}  # original filename → new filename

    for filename in pdf_files:
        path = os.path.join(WORK_DIR, filename)
        contract_number = extract_contract_number(path)

        if not contract_number:
            print(f"{filename:<45} {'→':^3} ⚠️  No contract number found — will be skipped")
            continue

        new_name = safe_filename(contract_number) + ".pdf"

        # Handle duplicates
        if new_name in preview_map.values() or (new_name != filename and os.path.exists(os.path.join(WORK_DIR, new_name))):
            base = safe_filename(contract_number)
            count = 1
            while f"{base}_{count}.pdf" in preview_map.values():
                count += 1
            new_name = f"{base}_{count}.pdf"

        preview_map[filename] = new_name
        status = "(same name)" if filename == new_name else ""
        print(f"{filename:<45} {'→':^3} {new_name}  {status}")

    print("─" * 90)
    print(f"\n✅ Preview complete. Run Cell 4 to apply renames and download.")

# ── CELL 4: Rename files and download as ZIP ──────────────────────────────────
import shutil

OUTPUT_DIR = "/content/pdfs_renamed"
os.makedirs(OUTPUT_DIR, exist_ok=True)

success = 0
skipped = 0
errors  = 0
used_names = set()

print("Renaming files...\n")

for filename in sorted(pdf_files):
    src_path = os.path.join(WORK_DIR, filename)
    contract_number = extract_contract_number(src_path)

    if not contract_number:
        print(f"  [SKIP] {filename} — no contract number found")
        skipped += 1
        continue

    new_name = safe_filename(contract_number) + ".pdf"

    # Handle duplicates
    if new_name in used_names:
        base = safe_filename(contract_number)
        count = 1
        while f"{base}_{count}.pdf" in used_names:
            count += 1
        new_name = f"{base}_{count}.pdf"

    used_names.add(new_name)
    dst_path = os.path.join(OUTPUT_DIR, new_name)

    try:
        shutil.copy2(src_path, dst_path)
        print(f"  [OK] {filename}  →  {new_name}")
        success += 1
    except Exception as e:
        print(f"  [ERROR] {filename}: {e}")
        errors += 1

print(f"\n{'─'*50}")
print(f"Done.  Renamed: {success}  |  Skipped: {skipped}  |  Errors: {errors}")

# Zip and download
zip_path = "/content/renamed_contracts"
shutil.make_archive(zip_path, "zip", OUTPUT_DIR)
print(f"\n📦 Downloading renamed_contracts.zip...")
files.download(zip_path + ".zip")