# -*- coding: utf-8 -*-
"""Addendum <> Contract Combine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJkZMAwfO3HWQvuJMdm2fQqxWKrRbZnp
"""

pip install PyPDF2

import os
import re
from google.colab import drive
from PyPDF2 import PdfWriter

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Configuration - Update these paths
# Use the folder icon on the left in Colab to find your folders,
# right-click them, and select 'Copy path'.
File_1_PATH = '/content/drive/MyDrive/your_path'
File_2_PATH = '/content/drive/MyDrive/your_path'
EXPORT_PATH    = '/content/drive/MyDrive/your_path'

os.makedirs(EXPORT_PATH, exist_ok=True)

def extract_contract_key(filename):
    """
    Hunts for IDs anywhere inside the filename.
    Matches: 'XXX_HR-PC_##_##' or 'XXX_##_ABC_DEFG_MM-YYYY_DD'
    """
    # 1. Classic Pattern: Looks for 4 digits + _HR-PC_ + Roman Numerals + _ + 2 digits
    # Removed strict boundaries so it finds it even inside "[Confidential]... (Ver 08)"
    classic_pattern = r'(\d{4}_HR-PC_[VIXLCDM]+_\d{2})'

    # 2. Modern Pattern: Looks for PKWT followed by the date/sequence string
    modern_pattern = r'(PKWT_[A-Z0-9_-]+_\d{2}-\d{4}_\d{2})'

    # Check for Classic match first
    match_classic = re.search(classic_pattern, filename)
    if match_classic:
        return match_classic.group(1)

    # Check for Modern match second
    match_modern = re.search(modern_pattern, filename)
    if match_modern:
        return match_modern.group(1)

    return None

def run_merge_process():
    contract_map = {}
    addendum_map = {}

    # Scan folders
    for path, mapping, label in [(File_1_PATH_PATH, contract_map, "File_1"),
                                (File_2_PATH_PATH, addendum_map, "File_2")]:
        print(f"--- Scanning {label} ---")
        if not os.path.exists(path):
            print(f"❌ Error: Path not found: {path}")
            continue

        for f in os.listdir(path):
            if f.lower().endswith('.pdf'):
                key = extract_contract_key(f)
                if key:
                    mapping[key] = f
                else:
                    # Useful for debugging which files are still being missed
                    print(f"Skipped: {f}")
        print(f"Total {label} identified: {len(mapping)}\n")

    print("-" * 50)
    matches_found = 0

    # Merge Logic
    for key in contract_map:
        if key in addendum_map:
            c_file = contract_map[key]
            a_file = addendum_map[key]
            output_name = f"Merged_{key}.pdf"

            merger = PdfWriter()
            try:
                merger.append(os.path.join(CONTRACTS_PATH, c_file))
                merger.append(os.path.join(ADDENDUMS_PATH, a_file))

                with open(os.path.join(EXPORT_PATH, output_name), "wb") as out:
                    merger.write(out)

                print(f"✅ SUCCESS: {key}")
                matches_found += 1
            except Exception as e:
                print(f"❌ ERROR merging {key}: {e}")
            finally:
                merger.close()

    print("-" * 50)
    print(f"Finished! Total merged files: {matches_found}")

run_merge_process()